# Generated by Django 4.1.1 on 2022-09-12 19:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(null=True, upload_to='profilepictures')),
                ('address', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SunType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverPhoto', models.ImageField(null=True, upload_to='coverphotos')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=300)),
                ('attendees', models.ManyToManyField(related_name='swaps', to='plantpalapi.plantpaluser')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantpalapi.plantpaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('water', models.IntegerField(default=1)),
                ('lastWatered', models.DateField(default=datetime.date.today)),
                ('petToxic', models.BooleanField()),
                ('notes', models.CharField(max_length=300)),
                ('sunType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantpalapi.suntype')),
                ('waterSpanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantpalapi.waterspan')),
            ],
        ),
    ]
