# Generated by Django 4.1.1 on 2022-09-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpalapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantPhoto',
            field=models.ImageField(null=True, upload_to='plantphotos'),
        ),
    ]
