# Generated by Django 4.1.1 on 2022-09-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantpalapi', '0002_plant_plantphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='title',
            field=models.CharField(default='Maypop Farm Swap', max_length=60),
            preserve_default=False,
        ),
    ]
