# Generated by Django 4.1.1 on 2022-09-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantpalapi', '0003_swap_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plantpalapi.plantpaluser'),
            preserve_default=False,
        ),
    ]
