# Generated by Django 4.1.1 on 2022-09-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantpalapi', '0004_plant_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_pic', models.ImageField(null=True, upload_to='plantimages')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='plantpalapi.plant')),
            ],
        ),
    ]
