# Generated by Django 4.1.1 on 2022-09-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantpalapi', '0005_plantphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantPhoto',
        ),
    ]
